spring.application.name=@project.release.name@-@project.api.version@
eam.application=@eam.application@
eam.component=@eam.component@


kb.speed.feature.rest.jax-rs.client.servicingBcClient.auto-registration=true
kb.speed.feature.rest.jax-rs.client.servicingBcClient.host=${be.servicing.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.servicingBcClient.uri=/api
kb.speed.feature.rest.jax-rs.client.servicingBcClient.realm=jwt

kb.speed.feature.rest.jax-rs.client.plcClient.auto-registration=true
kb.speed.feature.rest.jax-rs.client.plcClient.host=${be.plc.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.plcClient.uri=/api
kb.speed.feature.rest.jax-rs.client.plcClient.realm=jwt

kb.speed.feature.rest.jax-rs.client.t24Client.auto-registration=true
kb.speed.feature.rest.jax-rs.client.t24Client.host=${be.t24.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.t24Client.uri=/api
kb.speed.feature.rest.jax-rs.client.t24Client.key-store.type=JKS

kb.speed.feature.rest.jax-rs.client.ncaClient.auto-registration=true
kb.speed.feature.rest.jax-rs.client.ncaClient.host=${be.nca.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.ncaClient.uri=/api
kb.speed.feature.rest.jax-rs.client.ncaClient.realm=jwt
kb.speed.feature.security.jwt.tech.client.users.ncaServiceUser.scopes=nca_read

kb.speed.feature.rest.jax-rs.client.pricingClient.auto-registration=true
kb.speed.feature.rest.jax-rs.client.pricingClient.host=${be.pricing.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.pricingClient.uri=/api
kb.speed.feature.rest.jax-rs.client.pricingClient.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.pricingClient.timeout.read=2001ms
kb.speed.feature.rest.jax-rs.client.pricingClient.realm=jwt

kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.auto-registration=true
kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.host=${be.productDefinitions.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.uri=/api/product-definitions/v1
kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.timeout.read=2001ms
kb.speed.feature.rest.jax-rs.client.productDefinitionsClient.realm=jwt

# REST client PositionKeeping
kb.speed.feature.rest.jax-rs.client.positionKeepingClient.host=${be.positionKeeping.rest.endpoint}
kb.speed.feature.rest.jax-rs.client.positionKeepingClient.uri=/position-keeping/accounts/
kb.speed.feature.rest.jax-rs.client.positionKeepingClient.realm=positionKeepingRealm
kb.speed.feature.rest.jax-rs.client.positionKeepingClient.auto-registration=true
kb.speed.feature.rest.jax-rs.security.realm.positionKeepingRealm.type=BASIC

# JWT for rest clients
kb.speed.feature.http.auth.jwt.enabled=true
kb.speed.feature.rest.jax-rs.security.realm.jwt.type=OAUTH2

# jwk to verify jwt token, jwt generator: https://jwt-generator-v1.fat.caas-core.kbcloud/token
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://uat1-caas.kb.cz/openam/oauth2/realms/root/connect/jwk_uri

# CORS
kb.speed.feature.rest.cors.allowed-credentials=false
kb.speed.feature.rest.cors.allowed-origins=*
kb.speed.feature.rest.cors.allowed-headers=*
kb.speed.feature.rest.cors.allowed-methods=*

# Permission
kb.speed.feature.security.pep.baseUri=https://pdp.stage.perm.kbcloud/api/governance-engine

# Destination mapping for commandBus and queryBus
kb.speed.feature.messaging.cqrs.destination-mapping.cz.kb.leon.bff.servicing.app.command=InMemoryOutbound

# In memory broker
kb.speed.feature.messaging.brokers.in-memory.inmemorybroker.connection.replyTimeout=20
kb.speed.feature.messaging.brokers.in-memory.inmemorybroker.inbound.InMemoryInbound.queue=default-queue
kb.speed.feature.messaging.brokers.in-memory.inmemorybroker.outbound.InMemoryOutbound.queue=default-queue
kb.speed.feature.messaging.brokers.in-memory.inmemorybroker.outbound.InMemoryOutbound.default=true

# Flagsmith
flagsmith.enabled=true
flagsmith.cache.redis.enabled=false
flagsmith.flags.[feature.leon.overdraft_v2].enabled=false
flagsmith.flags.[feature.leon.operational_loan].enabled=false

flagsmith.annotations.feature-flag.enabled=true
flagsmith.annotations.feature-flag.party-relation-transformation-service.enabled=false

cob.start = ${bff.leon.servicing.cob.start}
cob.end = ${bff.leon.servicing.cob.end}
leon.servicing.zone-id.prague=Europe/Prague

# Exclude not our swaggers
kb.speed.feature.openapi.exclude-specifications=\
  bc-servicing-v1-api-jakarta, \
  AccountServicing-v1-api-jakarta, \
  bc-pricing-v1-api, \
  bc-pricing-v1-api-jakarta, \
  bc-productdefinition-private-v1-api-jakarta, \
  bc-productlifecycle-private-api-v1-api-jakarta, \
  bc-servicing-businessoverdraft-private-v1-api-jakarta, \
  bc-servicing-operationalloan-private-v1-api-jakarta, \
  bc-servicing-v2-api-jakarta