kb.speed.feature.tracing.zipkin.enabled=false
# Don't hide Authorization header on local
kb.speed.feature.rest.jax-rs.http-header-logging.headers=,

kb.speed.feature.security.jwt.tech.client.id=LEON_SERV_TECH_OAUTH
kb.speed.feature.security.jwt.tech.client.secret=password
kb.speed.feature.security.jwt.tech.client.base-uri=https://uat1-caas.kb.cz/openam/json/caas/api/technicalUser/v1/token?_action=getToken
kb.speed.feature.security.jwt.tech.client.users.bff-leon-servicing-service-user.username=bffLeonServServiceUser_d2
kb.speed.feature.security.jwt.tech.client.users.bff-leon-servicing-service-user.password=password
kb.speed.feature.security.jwt.tech.client.users.bff-leon-servicing-service-user.scopes=leon.serv:read,leon.serv:write,leon.serv:bff,leon.cont:read,leon.cont:write,leon.prop:read
kb.speed.feature.security.jwt.tech.client.users.ncaServiceUser.username=ncaServiceUser
kb.speed.feature.security.jwt.tech.client.users.ncaServiceUser.password=password

kb.speed.feature.rest.jax-rs.client.servicingBcClient.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.servicingBcClient.timeout.read=5s

kb.speed.feature.rest.jax-rs.client.plcClient.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.plcClient.timeout.read=5s

kb.speed.feature.rest.jax-rs.client.t24Client.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.t24Client.timeout.read=5s

kb.speed.feature.rest.jax-rs.client.ncaClient.timeout.connect=4s
kb.speed.feature.rest.jax-rs.client.ncaClient.timeout.read=5s

kb.speed.feature.rest.jax-rs.client.positionKeepingClient.timeout.connect=2s
kb.speed.feature.rest.jax-rs.client.positionKeepingClient.timeout.read=10s

kb.speed.feature.security.pep.baseUri=https://mockserver.devtools.leon.kbcloud/api/governance-engine
kb.speed.feature.security.pep.connect-timeout=2s
kb.speed.feature.security.pep.request-timeout=10s

bff.leon.servicing.cob.start=19:00:00
bff.leon.servicing.cob.end=22:00:00

flagsmith.enabled=true
flagsmith.config.url=https://flagsmith.kb.cz/api/v1/
flagsmith.config.apiKey=1234

be.plc.rest.endpoint=bc-productlifecycle-v1.fat.leon.kbcloud
be.t24.rest.endpoint=https://ti-leon-servicing.sit.t24.kbcloud/loans
be.nca.rest.endpoint=https://bc-accountservicing-v1.stage.nca.kbcloud/api/accounts
be.productDefinitions.rest.endpoint=https://bc-productdefinition-v1.fat.leon.kbcloud
kb.speed.feature.rest.jax-rs.client.t24Client.key-store.password=password
kb.speed.feature.rest.jax-rs.client.t24Client.key-store.class-path-resource=local_certs/kafka-bc-servicing.jks
be.positionKeeping.rest.endpoint=https://core-banking-sit.kb.cz
be.pricing.rest.endpoint=http://vncub27265.os.kb.cz:31151
